manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: MKP12e
      url-base: https://github.com/MKP12e
  projects:
    - name: zmk
      remote: MKP12e
      revision: MKP12e
      import: app/west.yml
  self:
    path: config
